import { StyleSheet } from "react-native";

const stylesGlobal = StyleSheet.create({
  gridTextContainerIfNumberIs2: {
    flex: 1,
    backgroundColor: "#ebe8da",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs4: {
    flex: 1,
    backgroundColor: "#e0dbc1",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs8: {
    flex: 1,
    backgroundColor: "#f5a164",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs16: {
    flex: 1,
    backgroundColor: "#ed8a42",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs32: {
    flex: 1,
    backgroundColor: "#f06c5d",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs64: {
    flex: 1,
    backgroundColor: "#ed4f3e",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs128: {
    flex: 1,
    backgroundColor: "#ede191",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs256: {
    flex: 1,
    backgroundColor: "#fae873",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs512: {
    flex: 1,
    backgroundColor: "#f2dd55",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  gridTextContainerIfNumberIs1024: {
    flex: 1,
    backgroundColor: "#f5db31",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  textContainerIfNumberIs1024: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#4d4646",
  },
  gridTextContainerIfNumberIs2048: {
    flex: 1,
    backgroundColor: "#f7ce52",
    margin: 5,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  textContainerIfNumberIs2048: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#4d4646",
  },
});

export { stylesGlobal };
